### ISSUE TITLE
replace for check_output: subprocess.run masks cli errors

### ISSUE THREAD

**Issue by phvalguima** [charmed-kubernetes/conctl#3]
Trying the code seen here: https://github.com/charmed-kubernetes/conctl/blob/master/conctl/base.py#L29

I can see: 
$ ctr image pull docker.io/calico/node:v3.6.1
ctr: failed to dial "/run/containerd/containerd.sock": context deadline exceeded

$ python3

Python 3.6.8 (default, Jan 14 2019, 11:02:34)
>>> import subprocess
>>> a=subprocess.run(["ctr","image","pull","docker.io/calico/node:v3.6.1"])
ctr: failed to dial "/run/containerd/containerd.sock": context deadline exceeded
>>> try:
...     a=subprocess.run(["ctr","image","pull","docker.io/calico/node:v3.6.1"])
... except:
...     print("it failed")
... 
ctr: failed to dial "/run/containerd/containerd.sock": context deadline exceeded
>>> try:
...     a=subprocess.check_output(["ctr","image","pull","docker.io/calico/node:v3.6.1"])
... except:
...     print("it failed")
... 
ctr: failed to dial "/run/containerd/containerd.sock": context deadline exceeded
it failed            <------------------------ failure is captured on except

If we keep run method, image pulling errors will fail way later on the code, when we actually try to do something with the image.

**Comment by joedborg** [comment]
Hi @phvalguima, I'm trying to understand what you're doing.

The error itself is almost certainly because you're not running as root (or a user with access to the .sock).  This is shown in the README https://github.com/charmed-kubernetes/conctl/blob/master/README.md#example.

If you're trying to script using `conctl`, you shouldn't be doing this via `subprocess`, you should import conctl and use the library as this will then propagate the exception, rather than printing it; also see https://github.com/charmed-kubernetes/conctl/blob/master/README.md#example

Could you elaborate a bit more please?

Thanks.

**Comment by phvalguima** [comment]
I am seeing calico-charm running conctl pull method on: https://github.com/charmed-kubernetes/layer-calico/blob/master/reactive/calico.py#L586

The issue that I'm facing is: charm is failing to pull the image. However, it does not raise an error at the moment of the pull command. Rather it fails way later when it tries to use the image.

I was digging on why no exception was raised and I've came up to this code: https://github.com/charmed-kubernetes/conctl/blob/master/conctl/base.py#L29

Essentially, pull method on conctl calls self._exec, which in turn, calls subprocess.run.

The problem of subprocess.run is that it won't care about process's return value by default (check is set as False by default). So either we move to subprocess.check_output or set check=True on run method: https://docs.python.org/3/library/subprocess.html#subprocess.run

My example above was to show run method does not capture the ctr error, whereas check_output captures and except content is called.

**Comment by joedborg** [comment]
Ah, thanks for clarifying @phvalguima, I understand now.  I'm not sure whether `conctl` should be raising an exception or the consumer should be checking the exit code in the returned object.  I guess the most pythonic way would be the exception route.

I'll add `check=True` when not piped (so the CLI continues to behave as it does now) and link this bug.

**Comment by joedborg** [comment]
https://github.com/charmed-kubernetes/conctl/pull/4

**Comment by joedborg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [conctl should raise exception on failed cli call](https://trello.com/c/jWf6APiz/1317-conctl-should-raise-exception-on-failed-cli-call)

**Comment by joedborg** [comment]
Released in version 0.0.23
